name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright chromium
      run: npx playwright install --with-deps chromium
    - name: Run Playwright tests
      run: npx playwright test
    - name: Generate Allure report
      run: npx allure generate --clean
    - name: Setup SSH
      env:
        PRIVATE_DEPLOY_KEY: ${{ secrets.PRIVATE_DEPLOY_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "${PRIVATE_DEPLOY_KEY}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Update github page with new report
      run: |
        git clone git@github.com:i-am-wizard/allure-ghpage.git
        git config --global user.email "i-am-wizard@github.com"
        git config --global user.name "i am wizard"
        
        cp -r allure-report/  allure-ghpage
      
        cd allure-ghpage
        git remote add dest git@github.com:i-am-wizard/allure-ghpage.git
        git add .
        git commit -m "pushed new allure report"
        git push dest
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: allure-report
        path: allure-report/
        retention-days: 30

